findpizzaria/src/main/java/br/edu/ifpb/findpizzaria/entity/Avaliacao.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.findpizzaria.entity;

/**
 *
 * @author jose
 */
public class Avaliacao {

    private Usuario usuario;
    String comentario;
  private int nota;
    private int idLocalidade;

    public Avaliacao() {
    }

    private Avaliacao(Usuario usuario, String comentario, int nota, int idLocalidade) {
        this.usuario = usuario;
        this.comentario = comentario;
        this.nota = nota;
        this.idLocalidade = idLocalidade;
    }
    /**
     * Método util para criar um objeto do tipo avalição
     * @param usuario
     * @param comentario
     * @param nota
     * @param idLocalidade
     * @return Objeto do tipo Avaliação
     */
     public static Avaliacao of(Usuario usuario, String comentario, int nota, int idLocalidade) {
         validarNota(nota);
        return new Avaliacao(usuario, comentario, nota, idLocalidade);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getComentario() {
        return comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    public int getNota() {
        return nota;
    }

    public void setNota(int nota) {
        validarNota(nota);
        this.nota = nota;
    }

    public int getIdLocalidade() {
        return idLocalidade;
    }

    public void setIdLocalidade(int idLocalidade) {
        this.idLocalidade = idLocalidade;
    }
private static void validarNota(int nota){
    if(nota<0 || nota>10)
         throw new IllegalArgumentException("Digite uma nota entre 1 e 10 ");
}
    @Override
    public String toString() {
        return "Avaliacao{" + "usuario=" + usuario + ", comentario=" + comentario + ", nota=" + nota + ", idLocalidade=" + idLocalidade + '}';
    }
    

}

findpizzaria/src/main/java/br/edu/ifpb/findpizzaria/entity/Localidade.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.findpizzaria.entity;

import com.vividsolutions.jts.geom.Geometry;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author jose
 */
public class Localidade {

    private int id;
    private String nome;
    private String endereco;

    private Geometry location;

    private double mediaNotas;
     private String telefone;
   private List<Avaliacao> avaliacao;

    public Localidade() {
    }

    private Localidade(int id, String nome, String endereco, Geometry location, double mediaNotas, String telefone) {
        this.id = id;
        this.nome = nome;
        this.endereco = endereco;
        this.location = location;
        this.mediaNotas = mediaNotas;
        this.telefone = telefone;
       
    }
    private Localidade( String nome, String endereco, Geometry location, double mediaNotas, String telefone) {
       
        this.nome = nome;
        this.endereco = endereco;
        this.location = location;
        this.mediaNotas = mediaNotas;
        this.telefone = telefone;
      
    }
    /**
     * Método util para criar um objeto do tipo localidade
     * @param id
     * @param nome
     * @param endereco
     * @param location
     * @param mediaNotas
     * @param telefone
   
     * @return Objeto do tipo Localidade
     */
   public static Localidade of(int id, String nome, String endereco, Geometry location, double mediaNotas, String telefone, List<Avaliacao> avaliacao) {
       return new Localidade(id, nome, endereco, location, mediaNotas, telefone);
   }
    /**
     * Método util para criar um objeto do tipo localidade
     * @param nome
     * @param endereco
     * @param location
     * @param mediaNotas
     * @param telefone
     * @return Objeto do tipo Localidade
     */
    public static Localidade of( String nome, String endereco, Geometry location, double mediaNotas, String telefone, List<Avaliacao> avaliacao) {
       return new Localidade(nome, endereco, location, mediaNotas, telefone);
   }
       
    

   

    public int getId() {
        return id;
    }

  

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEndereco() {
        return endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public Geometry getLocation() {
        return location;
    }

    public void setLocation(Geometry location) {
        this.location = location;
    }

    public double getMediaNotas() {
        return mediaNotas;
    }

    public void setMediaNotas(double mediaNotas) {
        this.mediaNotas = mediaNotas;
    }

    public String getTelefone() {
        return telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public List<Avaliacao> getAvaliacao() {
        return Collections.unmodifiableList(avaliacao);
    }

    public void setAvaliacao(List<Avaliacao> avaliacao) {
        this.avaliacao = avaliacao;
    }

    @Override
    public String toString() {
        return "Localidade{" + "id=" + id + ", nome=" + nome + ", endereco=" + endereco + ", location=" + location + ", mediaNotas=" + mediaNotas + ", telefone=" + telefone + ", avaliacao=" + avaliacao + '}';
    }

}

findpizzaria/src/main/java/br/edu/ifpb/findpizzaria/entity/Usuario.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.findpizzaria.entity;

import javax.inject.Named;

/**
 *
 * @author jose
 */
@Named
public class Usuario {

    private int id;
    private String nome;
    private String email;
    private String senha;

    public Usuario() {
    }

    private Usuario(int id, String nome, String email, String senha) {
        this.id = id;
        this.nome = nome;
        this.email = email;
        this.senha = senha;
    }

    private Usuario(String nome, String email, String senha) {

        this.nome = nome;
        this.email = email;
        this.senha = senha;
    }

    /**
     * Método util para criar um objeto do tipo Usuario
     *
     * @param id
     * @param nome
     * @param email
     * @param senha
     * @return retorna um objeto do tipo Usuario
     */
    public static Usuario of(int id, String nome, String email, String senha) {
        return new Usuario(id, nome, email, senha);
    }

    /**
     * Método util para criar um objeto do tipo Usuario
     *
     * @param nome
     * @param email
     * @param senha
     * @return retorna um objeto do tipo Usuario
     */
    public static Usuario of(String nome, String email, String senha) {
        return new Usuario(nome, email, senha);
    }

    public int getId() {
        return id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    @Override
    public String toString() {
        return "Usuario{" + "id=" + id + ", nome=" + nome + ", email=" + email + ", senha=" + senha + '}';
    }
    

}

findpizzaria/src/main/java/br/edu/ifpb/findpizza/controller/Controller.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.findpizza.controller;

import br.edu.ifpb.findpizza.util.Mensagem;
import br.edu.ifpb.findpizzaria.entity.Localidade;
import br.edu.ifpb.findpizzaria.entity.Usuario;
import br.edu.ifpb.findpizzaria.service.LocalidadeService;
import br.edu.ifpb.findpizzaria.service.UserService;
import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.io.ParseException;
import com.vividsolutions.jts.io.WKTReader;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose
 */
@Named
@RequestScoped
public class Controller {

    private LocalidadeService sl;
    private Localidade localidade;
    private UserService su;
    private String nome;
    @Inject
    private Mensagem mensagem;

    public Controller() {

    }

    @PostConstruct
    public void init() {
        sl = new LocalidadeService();
        localidade = new Localidade();
        su = new UserService();
    }

    public String save() throws ParseException {
        try {
             WKTReader fromText = new WKTReader();

        Geometry geom = fromText.read("POINT(23 43)");
        localidade = Localidade.of(nome, "end 1", geom, 0, "21444", null);

        sl.salve(localidade);
        localidade = new Localidade();
        mensagem.addMessage(nome+": savo com sucesso");
        } catch (Exception e) {
            mensagem.addMessage("erro ao sava "+ e.getMessage());
        }
        return null;
    }

    public Localidade getLocalidade() {
        return localidade;
    }

    public void setLocalidade(Localidade localidade) {
        this.localidade = localidade;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }
    public List<Usuario> getUsuarios(){
        List<Usuario> buscarTodos = new ArrayList<>();
        buscarTodos.add(su.buscar("id", 1));
//        for (Usuario b : buscarTodos) {
//            System.err.println("usario"+b);
//        }
        return buscarTodos;
    }    
//    public List<Usuario> getUsuarios(){
//        List<Usuario> buscarTodos = su.buscarTodos();
//        for (Usuario b : buscarTodos) {
//            System.err.println("usario"+b);
//        }
//        return buscarTodos;
//    }    

}

findpizzaria/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Find Pizzaria</title>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no"></meta>
        <meta charset="utf-8"></meta>
        <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet"></link>
        <link href="bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet"></link>
        <link href="bootstrap-3.3.7-dist/css/newCascadeStyleSheet.css" rel="stylesheet"></link>
        <script type="text/javascript" src="bootstrap-3.3.7-dist/js/jquery-3.2.1.js"></script>
        <script type="text/javascript" src="bootstrap-3.3.7-dist/js/newjavascript.js"></script> 
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFlK-O5FhzwKxvG0GLLxHpPcQ9H1qN8EY"></script>

    </h:head>
    <body>
        <div id="menu">
            <h:form class="navbar  navbar-light bg-light">
                <div class="form-inline">
                    <p:outputLabel value="FIND PIZZA's" style="padding-left: 40px"></p:outputLabel>
                    <p:outputLabel styleClass="em em-pizza"></p:outputLabel>
                     <p:messages showDetail="true" showIcon="false" closable="true" showSummary="false" autoUpdate="false"/>
      
                    <a href="#" id="login" style="padding-left: 40px; padding-right: 40px; color: white">login</a>
                    <p:inputText styleClass="form-control mr-sm-2" placeholder="busca"></p:inputText>
                    <button   id="btnbusca" type="button" class="btn btn-link active">
                        <i class="em em-mag_right"></i>
                    </button>
                </div>
            </h:form>
        </div>
        <center id="cadastro">
            <p:panel styleClass="navbar" style=" width: 30%; background: -webkit-gradient(linear, left top, left bottom, from(#122b40), to(#000000));
                     background: -moz-linear-gradient(top, #122b40, #000000);
                     filter:progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr='#122b40', EndColorStr='#000000');" >
                <h:form styleClass="form-group " id="cadastro">
                    <label class="btn btn-default form-control">Cadastro</label><br></br><br></br>
                    <div class="input-group mb-2 mb-sm-0">
                        <div class=" input-group-addon">
                            <i class="em em-bust_in_silhouette"></i>
                        </div>
                        <h:inputText styleClass="form-control"></h:inputText>
                    </div><br></br>
                    <div class="input-group mb-2 mb-sm-0">
                        <div class=" input-group-addon">
                            <i class="em em-envelope_with_arrow"></i>
                        </div>
                        <h:inputText styleClass="form-control" ></h:inputText>
                    </div><br></br>
                    <div class="input-group mb-2 mb-sm-0">
                        <div class=" input-group-addon">
                            <i class="em em-closed_lock_with_key"></i>
                        </div>
                        <p:password styleClass="form-control"></p:password>
                    </div><br></br>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <p:commandButton styleClass="btn btn-secondary" value="Enviar"></p:commandButton>
                        <p:button id="cancelarlogin" styleClass="btn btn-secondary" value="Cancelar"></p:button>
                    </div>
                </h:form>
            </p:panel>
        </center>
        <center  id="logar">
            <p:panel styleClass="navbar" style=" width: 30%; background: -webkit-gradient(linear, left top, left bottom, from(#122b40), to(#000000));
                     background: -moz-linear-gradient(top, #122b40, #000000);
                     filter:progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr='#122b40', EndColorStr='#000000');" >
                <h:form styleClass="form-group ">
                    <label class="btn btn-default form-control">Login</label><br></br><br></br>
                    <div class="input-group mb-2 mb-sm-0">
                        <div class=" input-group-addon">
                            <i class="em em-envelope_with_arrow"></i>
                        </div>
                        <h:inputText styleClass="form-control" value="#{userLogin.login}"/>
                    </div><br></br>
                    <div class="input-group mb-2 mb-sm-0">
                        <div class=" input-group-addon">
                            <i class="em em-closed_lock_with_key"></i>
                        </div>
                        <p:password styleClass="form-control" value="#{userLogin.password}"/>
                    </div><br></br>

                    <div class="btn-group" role="group" aria-label="Basic example">
                        <p:commandButton styleClass="btn btn-secondary" action="#{userLogin.logar()}" value="Enviar"></p:commandButton>
                        <p:button id="cancelarlogin" styleClass="btn btn-secondary" value="Cancelar"></p:button>
                    </div><br></br><br></br>
                    <a href="#" id="fazercadastro"  Class="badge">Cadastre-se Aqui</a>

                </h:form>
            </p:panel>
        </center>
        <p:gmap center="41.381542, 2.122893" zoom="15" type="HYBRID" style="width:100%;height:400px" id="map"/>
        <a href="teste.xhtml">dada</a>
    </body>
</html>

findpizzaria/src/main/webapp/teste.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
        <link href="bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet"></link>
    </h:head>
    <h:body>
        Hello from Facelets
        <h:form>
             <h:dataTable value ="#{controller.usuarios}" var = "func">
		<h:column>
			<h:outputText value="#{func.nome}"/>
		</h:column>
		<h:column>
                    <h:outputText value="#{func.email}"/>
		</h:column>
		
	</h:dataTable>
        </h:form>
        <h:form>
            
         <p:messages showDetail="true" showIcon="false" closable="true" showSummary="false" autoUpdate="false"/>
        <h:inputText value="#{controller.nome}"/>
        <h:commandButton action="#{controller.save()}" value="salvar"/>
        </h:form>
    </h:body>
</html>

findpizzaria/src/main/webapp/viewAvaliacao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        ola Jose
    </h:body>
</html>